version: '3.7'

services:

  sms_worker:
    build:
      context: ../sms-worker
      dockerfile: Dockerfile.dev
    volumes:
      - "../sms-worker:/go/src/github.com/nuucactus/sms-worker"
    networks:
      - private
    restart: on-failure

  sms_api:
    build:
      context: ../sms-api
      dockerfile: Dockerfile.dev
    volumes:
      - "../sms-api:/go/src/github.com/nuucactus/sms-api"
    networks:
      - public
      - private
    ports:
      - "8080:8080"
    restart: on-failure

networks:
  public:
    name: public
    internal: false
  private:
    name: private
    internal: true
